#!/usr/bin/env bats
#
# BATS Test Suite: BASIC
# Generated by CLI Testing Specialist
# Target CLI: cli.js
#

# Setup function (runs before each test)
setup() {
    # Set CLI binary path
    CLI_BINARY="/Users/sanae.abe/projects/package-publisher/dist/cli.js"
    BINARY_BASENAME="cli.js"

    # Export CLI_BINARY for subshell tests (multi-shell compatibility)
    export CLI_BINARY

    # Create temporary directory for test artifacts
    TEST_TEMP_DIR="$(mktemp -d)"
    export TEST_TEMP_DIR

    # Set secure umask
    umask 077
}

# Teardown function (runs after each test)
teardown() {
    # Cleanup temporary directory
    if [[ -n "${TEST_TEMP_DIR:-}" ]] && [[ -d "$TEST_TEMP_DIR" ]]; then
        rm -rf "$TEST_TEMP_DIR"
    fi
}

@test "[basic] Display help with --help flag" {
    # Test ID: basic-001
    # Tags: help

    # Execute command
    run "$CLI_BINARY" --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[basic] Display help with -h flag" {
    # Test ID: basic-002
    # Tags: help

    # Execute command
    run "$CLI_BINARY" -h

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[basic] Display version with --version flag" {
    # Test ID: basic-003
    # Tags: version

    # Execute command
    run "$CLI_BINARY" --version

    # Assert exit code
    [ "$status" -eq 0 ]
}

@test "[basic] Reject invalid option" {
    # Test ID: basic-004
    # Tags: error-handling

    # Execute command
    run "$CLI_BINARY" --invalid-option-xyz

    # Assert exit code
    [ "$status" -ne 0 ]

    # Additional assertions
    [[ "$output" =~ "error" ]] || [[ "$stderr" =~ "error" ]]
}

@test "[basic] Require subcommand when invoked without arguments" {
    # Test ID: basic-005
    # Tags: no-args, require-subcommand

    # Execute command
    run "$CLI_BINARY"

    # Assert exit code
    [ "$status" -ne 0 ]
}

