#!/usr/bin/env bats
#
# BATS Test Suite: HELP
# Generated by CLI Testing Specialist
# Target CLI: cli.js
#

# Setup function (runs before each test)
setup() {
    # Set CLI binary path
    CLI_BINARY="/Users/sanae.abe/projects/package-publisher/dist/cli.js"
    BINARY_BASENAME="cli.js"

    # Export CLI_BINARY for subshell tests (multi-shell compatibility)
    export CLI_BINARY

    # Create temporary directory for test artifacts
    TEST_TEMP_DIR="$(mktemp -d)"
    export TEST_TEMP_DIR

    # Set secure umask
    umask 077
}

# Teardown function (runs after each test)
teardown() {
    # Cleanup temporary directory
    if [[ -n "${TEST_TEMP_DIR:-}" ]] && [[ -d "$TEST_TEMP_DIR" ]]; then
        rm -rf "$TEST_TEMP_DIR"
    fi
}

@test "[help] Display help for subcommand 'publish'" {
    # Test ID: help-001
    # Tags: subcommand-help, publish

    # Execute command
    run "$CLI_BINARY" publish --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'check'" {
    # Test ID: help-002
    # Tags: subcommand-help, check

    # Execute command
    run "$CLI_BINARY" check --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'stats'" {
    # Test ID: help-003
    # Tags: subcommand-help, stats

    # Execute command
    run "$CLI_BINARY" stats --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'report'" {
    # Test ID: help-004
    # Tags: subcommand-help, report

    # Execute command
    run "$CLI_BINARY" report --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

