#!/usr/bin/env bats
#
# BATS Test Suite: PERFORMANCE
# Generated by CLI Testing Specialist
# Target CLI: cli.js
#

# Setup function (runs before each test)
setup() {
    # Set CLI binary path
    CLI_BINARY="/Users/sanae.abe/projects/package-publisher/dist/cli.js"
    BINARY_BASENAME="cli.js"

    # Export CLI_BINARY for subshell tests (multi-shell compatibility)
    export CLI_BINARY

    # Create temporary directory for test artifacts
    TEST_TEMP_DIR="$(mktemp -d)"
    export TEST_TEMP_DIR

    # Set secure umask
    umask 077
}

# Teardown function (runs after each test)
teardown() {
    # Cleanup temporary directory
    if [[ -n "${TEST_TEMP_DIR:-}" ]] && [[ -d "$TEST_TEMP_DIR" ]]; then
        rm -rf "$TEST_TEMP_DIR"
    fi
}

@test "[performance] Startup time for --help < 100ms" {
    # Test ID: perf-001
    # Tags: startup, benchmark

    # Execute command
    run "$CLI_BINARY" --help

    # Assert exit code
    [ "$status" -eq 0 ]
}

@test "[performance] Memory usage stays within reasonable limits" {
    # Test ID: perf-002
    # Tags: memory, benchmark

    # Execute command
    run "$CLI_BINARY" --help

    # Assert exit code
    [ "$status" -eq 0 ]
}

