#!/usr/bin/env bats
#
# BATS Test Suite: SECURITY
# Generated by CLI Testing Specialist
# Target CLI: cli.js
#

# Setup function (runs before each test)
setup() {
    # Set CLI binary path
    CLI_BINARY="/Users/sanae.abe/projects/package-publisher/dist/cli.js"
    BINARY_BASENAME="cli.js"

    # Export CLI_BINARY for subshell tests (multi-shell compatibility)
    export CLI_BINARY

    # Create temporary directory for test artifacts
    TEST_TEMP_DIR="$(mktemp -d)"
    export TEST_TEMP_DIR

    # Set secure umask
    umask 077
}

# Teardown function (runs after each test)
teardown() {
    # Cleanup temporary directory
    if [[ -n "${TEST_TEMP_DIR:-}" ]] && [[ -d "$TEST_TEMP_DIR" ]]; then
        rm -rf "$TEST_TEMP_DIR"
    fi
}

@test "[security] Reject command injection in option value" {
    # Test ID: security-001
    # Tags: injection, critical

    # Execute command
    run "$CLI_BINARY" --invalid-option 'test; rm -rf /'

    # Assert exit code
    [ "$status" -ne 0 ]
}

@test "[security] Reject null byte in option value" {
    # Test ID: security-002
    # Tags: injection, critical

    # Execute command
    run "$CLI_BINARY" --invalid-option $'/tmp/test\x00malicious'

    # Assert exit code
    [ "$status" -ne 0 ]
}

@test "[security] Reject path traversal attempt" {
    # Test ID: security-003
    # Tags: path-traversal, critical

    # Execute command
    run "$CLI_BINARY" --invalid-option ../../../etc/passwd

    # Assert exit code
    [ "$status" -ne 0 ]
}

